include: package:flutter_lints/flutter.yaml
linter:
  rules:
    # Style and formatting
    avoid_annotating_with_dynamic: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    avoid_print: true
    unnecessary_this: true
    type_init_formals: true
    prefer_single_quotes: true

    # Naming conventions
    camel_case_types: true # Classes, enums, typedefs, mixins in PascalCase
    constant_identifier_names: true # Constants in ALL_CAPS_WITH_UNDERSCORES
    file_names: true # File names in snake_case
    library_names: true
    non_constant_identifier_names: false

    # Code structure
    one_member_abstracts: true
    no_leading_underscores_for_local_identifiers: true

    # Misc
    avoid_unused_constructor_parameters: true
    no_duplicate_case_values: true
    unnecessary_new: true
    use_key_in_widget_constructors: true
    always_use_package_imports: true
