name: streamkeys
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  window_manager: ^0.4.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  reorderables: ^0.6.0
  network_discovery: ^1.0.0
  device_info_plus: ^10.1.2
  tray_manager: ^0.2.3
  flutter_colorpicker: ^1.1.0
  process_run: ^1.2.0+3
  path: ^1.9.0
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
