name: streamkeys
description: "StreamKeys is a cross-platform application that allows you to configure and control actions on a Windows computer using a keyboard or an Android mobile device or Web over a local Wi-Fi network."
publish_to: "none"
version: 3.0.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  shared_preferences_platform_interface: ^2.4.1
  flutter_resizable_container: ^4.2.0
  path_provider: ^2.1.5
  mockito: ^5.4.6
  build_runner: ^2.5.0
  flutter_colorpicker: ^1.1.0
  uuid: ^4.5.1
  dotted_border: ^2.1.0
  file_picker: ^10.2.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  flutter_secure_storage: ^9.2.4
  dropdown_button2: ^2.3.9
  xml: ^6.5.0
  path: ^1.9.1
  obs_websocket: ^5.2.3
  intl: ^0.20.2
  audioplayers: ^6.5.0
  crypto: ^3.0.6
  http: ^1.4.0
  mime: ^2.0.0
  native_device_orientation: ^2.0.3
  args: ^2.7.0
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/keyboard_map.json
    - assets/keyboard_key_codes.json
    - assets/action_icons/
    - assets/action_icons/streamerbot.png
    - assets/hidmacros/
    - assets/hidmacros/lang/
    - assets/hidmacros/xpl/
    - assets/sounds/
    - assets/click_button.exe
