// Mocks generated by Mockito 5.4.6 from annotations
// in streamkeys/test/mobile/api_connection_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i2;
import 'package:streamkeys/core/storage/connection_settings_repository.dart'
    as _i3;
import 'package:streamkeys/core/storage/secure_storable.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ConnectionSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionSettingsRepository<T extends _i1.SecureStorable>
    extends _i2.Mock implements _i3.ConnectionSettingsRepository<T> {
  MockConnectionSettingsRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i4.Future<T?> loadConnectionData() => (super.noSuchMethod(
        Invocation.method(
          #loadConnectionData,
          [],
        ),
        returnValue: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  _i4.Future<void> saveConnectionData(T? data) => (super.noSuchMethod(
        Invocation.method(
          #saveConnectionData,
          [data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
