name: CI/CD for Development Branch

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 23 for Java development
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "23"

      # Step 3: Set up Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"

      # Step 4: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Analyze the code for issues
      - name: Analyze code
        run: flutter analyze
