name: CI/CD for Development Branch

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 23 for Java development
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "23"

      # Step 3: Set up Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"

      # Step 4: Install Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Analyze the code for issues
      - name: Analyze code
        run: flutter analyze

      # Step 6: Build the Android app (debug version)
      - name: Build the Android app
        run: flutter build apk --debug

      # Step 7: Copy the generated Android APK to a new location
      - name: Copy Android APK
        run: |
          mkdir -p build/debug
          copy "build\app\outputs\flutter-apk\app-debug.apk" "build\debug\StreamKeys-Android-Debug.apk"

      # Step 8: Upload the generated Android APK as an artifact
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: StreamKeys-Android-Debug.apk
          path: build/debug/StreamKeys-Android-Debug.apk

      # Step 9: Build the Windows app (debug version)
      - name: Build Windows app
        run: flutter build windows --debug

      # Step 10: Archive the Windows build
      - name: Archive Windows Build
        run: |
          powershell Compress-Archive -Path "build\windows\x64\runner\Debug\*" -DestinationPath "build\debug\StreamKeys-Windows-Debug.zip"

      # Step 11: Upload the Windows build as an artifact
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: StreamKeys-Windows-Debug.zip
          path: build/debug/StreamKeys-Windows-Debug.zip
