name: Flutter CI

on:
  push:
    branches:
      - main
      - development
      - v3-rewrite
  pull_request:
    branches:
      - main
      - development
      - v3-rewrite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub
